#pragma once

#include "usb.h"
#include "defs.h"

typedef struct {
	u16 left[ROW_COUNT][COL_COUNT];
	u16 right[ROW_COUNT][COL_COUNT];
} keymap_layer_t;

typedef struct {
	keymap_layer_t layers[LAYER_COUNT];
} keymap_t;

extern const keymap_t PROGMEM keymap;

#define KEYMAP_LAYER( \
	KA01, KA02, KA03, KA04, KA05, KA06,       /**/       KA09, KA10, KA11, KA12, KA13, KA14, \
	KB01, KB02, KB03, KB04, KB05, KB06, KB07, /**/ KB08, KB09, KB10, KB11, KB12, KB13, KB14, \
	KC01, KC02, KC03, KC04, KC05, KC06, KC07, /**/ KC08, KC09, KC10, KC11, KC12, KC13, KC14, \
	KD01, KD02, KD03, KD04, KD05, KD06, KD07, /**/ KD08, KD09, KD10, KD11, KD12, KD13, KD14, \
	      KE02, KE03, KE04, KE05, KE06, KE07, /**/ KE08, KE09, KE10, KE11, KE12, KE13        \
) { \
	.left = { \
		{ KEYMAP_KEY_##KA01, KEYMAP_KEY_##KA02, KEYMAP_KEY_##KA03, KEYMAP_KEY_##KA04, KEYMAP_KEY_##KA05, KEYMAP_KEY_##KA06, KEYMAP_KEY_NULL   }, \
		{ KEYMAP_KEY_##KB01, KEYMAP_KEY_##KB02, KEYMAP_KEY_##KB03, KEYMAP_KEY_##KB04, KEYMAP_KEY_##KB05, KEYMAP_KEY_##KB06, KEYMAP_KEY_##KB07 }, \
		{ KEYMAP_KEY_##KC01, KEYMAP_KEY_##KC02, KEYMAP_KEY_##KC03, KEYMAP_KEY_##KC04, KEYMAP_KEY_##KC05, KEYMAP_KEY_##KC06, KEYMAP_KEY_##KC07 }, \
		{ KEYMAP_KEY_##KD01, KEYMAP_KEY_##KD02, KEYMAP_KEY_##KD03, KEYMAP_KEY_##KD04, KEYMAP_KEY_##KD05, KEYMAP_KEY_##KD06, KEYMAP_KEY_##KD07 }, \
		{ KEYMAP_KEY_NULL,   KEYMAP_KEY_##KE02, KEYMAP_KEY_##KE03, KEYMAP_KEY_##KE04, KEYMAP_KEY_##KE05, KEYMAP_KEY_##KE06, KEYMAP_KEY_##KE07 }, \
	}, \
	.right = { \
		{ KEYMAP_KEY_NULL,   KEYMAP_KEY_##KA09, KEYMAP_KEY_##KA10, KEYMAP_KEY_##KA11, KEYMAP_KEY_##KA12, KEYMAP_KEY_##KA13, KEYMAP_KEY_##KA14 }, \
		{ KEYMAP_KEY_##KB08, KEYMAP_KEY_##KB09, KEYMAP_KEY_##KB10, KEYMAP_KEY_##KB11, KEYMAP_KEY_##KB12, KEYMAP_KEY_##KB13, KEYMAP_KEY_##KB14 }, \
		{ KEYMAP_KEY_##KC08, KEYMAP_KEY_##KC09, KEYMAP_KEY_##KC10, KEYMAP_KEY_##KC11, KEYMAP_KEY_##KC12, KEYMAP_KEY_##KC13, KEYMAP_KEY_##KC14 }, \
		{ KEYMAP_KEY_##KD08, KEYMAP_KEY_##KD09, KEYMAP_KEY_##KD10, KEYMAP_KEY_##KD11, KEYMAP_KEY_##KD12, KEYMAP_KEY_##KD13, KEYMAP_KEY_##KD14 }, \
		{ KEYMAP_KEY_##KE08, KEYMAP_KEY_##KE09, KEYMAP_KEY_##KE10, KEYMAP_KEY_##KE11, KEYMAP_KEY_##KE12, KEYMAP_KEY_##KE13, KEYMAP_KEY_NULL   }, \
	}, \
}

#define KEYMAP_CODE_MASK     0xFF
#define KEYMAP_HARDWARE_KEY  _BV(8)
#define KEYMAP_UNSHIFTED_KEY _BV(9)
#define KEYMAP_SHIFTED_KEY   _BV(10)
#define KEYMAP_LAYER_SHIFT   _BV(11)

#define KEYMAP_KEY_NULL 0

#define KEYMAP_KEY_LAYER_SHIFT(n)  (n | KEYMAP_LAYER_SHIFT)

#define KEYMAP_KEY_A (HID_KEYBOARD_A | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_B (HID_KEYBOARD_B | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_C (HID_KEYBOARD_C | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_D (HID_KEYBOARD_D | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_E (HID_KEYBOARD_E | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F (HID_KEYBOARD_F | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_G (HID_KEYBOARD_G | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_H (HID_KEYBOARD_H | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_I (HID_KEYBOARD_I | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_J (HID_KEYBOARD_J | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_K (HID_KEYBOARD_K | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_L (HID_KEYBOARD_L | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_M (HID_KEYBOARD_M | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_N (HID_KEYBOARD_N | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_O (HID_KEYBOARD_O | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_P (HID_KEYBOARD_P | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_Q (HID_KEYBOARD_Q | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_R (HID_KEYBOARD_R | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_S (HID_KEYBOARD_S | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_T (HID_KEYBOARD_T | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_U (HID_KEYBOARD_U | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_V (HID_KEYBOARD_V | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_W (HID_KEYBOARD_W | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_X (HID_KEYBOARD_X | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_Y (HID_KEYBOARD_Y | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_Z (HID_KEYBOARD_Z | KEYMAP_HARDWARE_KEY)

#define KEYMAP_KEY_1_BANG      (HID_KEYBOARD_1_BANG      | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_1           (HID_KEYBOARD_1_BANG      | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_BANG        (HID_KEYBOARD_1_BANG      | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_2_AT        (HID_KEYBOARD_2_AT        | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_2           (HID_KEYBOARD_2_AT        | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_AT          (HID_KEYBOARD_2_AT        | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_3_HASH      (HID_KEYBOARD_3_HASH      | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_3           (HID_KEYBOARD_3_HASH      | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_HASH        (HID_KEYBOARD_3_HASH      | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_4_DOLLAR    (HID_KEYBOARD_4_DOLLAR    | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_4           (HID_KEYBOARD_4_DOLLAR    | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_DOLLAR      (HID_KEYBOARD_4_DOLLAR    | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_5_PERCENT   (HID_KEYBOARD_5_PERCENT   | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_5           (HID_KEYBOARD_5_PERCENT   | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_PERCENT     (HID_KEYBOARD_5_PERCENT   | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_6_CARET     (HID_KEYBOARD_6_CARET     | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_6           (HID_KEYBOARD_6_CARET     | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_CARET       (HID_KEYBOARD_6_CARET     | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_7_AMPERSAND (HID_KEYBOARD_7_AMPERSAND | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_7           (HID_KEYBOARD_7_AMPERSAND | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_AMPERSAND   (HID_KEYBOARD_7_AMPERSAND | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_8_ASTERISK  (HID_KEYBOARD_8_ASTERISK  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_8           (HID_KEYBOARD_8_ASTERISK  | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_ASTERISK    (HID_KEYPAD_ASTERISK      | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_9_LPAREN    (HID_KEYBOARD_9_LPAREN    | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_9           (HID_KEYBOARD_9_LPAREN    | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_LPAREN      (HID_KEYBOARD_9_LPAREN    | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_0_RPAREN    (HID_KEYBOARD_0_RPAREN    | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_0           (HID_KEYBOARD_0_RPAREN    | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_RPAREN      (HID_KEYBOARD_0_RPAREN    | KEYMAP_SHIFTED_KEY)

#define KEYMAP_KEY_RETURN    (HID_KEYBOARD_ENTER     | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_ESC       (HID_KEYBOARD_ESCAPE    | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_BACKSPACE (HID_KEYBOARD_BACKSPACE | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_TAB       (HID_KEYBOARD_TAB       | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_SPACE     (HID_KEYBOARD_SPACE     | KEYMAP_HARDWARE_KEY)

#define KEYMAP_KEY_DASH_UNDERSCORE (HID_KEYBOARD_DASH_UNDERSCORE  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_DASH            (HID_KEYPAD_DASH               | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_UNDERSCORE      (HID_KEYBOARD_DASH_UNDERSCORE  | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_EQUAL_PLUS      (HID_KEYBOARD_EQUAL_PLUS       | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_EQUAL           (HID_KEYBOARD_EQUAL_PLUS       | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_PLUS            (HID_KEYPAD_PLUS               | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_LBRACKET_LBRACE (HID_KEYBOARD_LBRACKET_LBRACE  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_LBRACKET        (HID_KEYBOARD_LBRACKET_LBRACE  | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_LBRACE          (HID_KEYBOARD_LBRACKET_LBRACE  | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_RBRACKET_RBRACE (HID_KEYBOARD_RBRACKET_RBRACE  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_RBRACKET        (HID_KEYBOARD_RBRACKET_RBRACE  | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_RBRACE          (HID_KEYBOARD_RBRACKET_RBRACE  | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_BACKSLASH_PIPE  (HID_KEYBOARD_BACKSLASH_PIPE   | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_BACKSLASH       (HID_KEYBOARD_BACKSLASH_PIPE   | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_PIPE            (HID_KEYBOARD_BACKSLASH_PIPE   | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_SEMICOLON_COLON (HID_KEYBOARD_SEMICOLON_COLON  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_SEMICOLON       (HID_KEYBOARD_SEMICOLON_COLON  | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_COLON           (HID_KEYBOARD_SEMICOLON_COLON  | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_QUOTE_DOUBLE    (HID_KEYBOARD_APOSTROPHE_QUOTE | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_QUOTE           (HID_KEYBOARD_APOSTROPHE_QUOTE | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_DOUBLEQUOTE     (HID_KEYBOARD_APOSTROPHE_QUOTE | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_GRAVE_TILDE     (HID_KEYBOARD_BACKTICK_TILDE   | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_GRAVE           (HID_KEYBOARD_BACKTICK_TILDE   | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_TILDE           (HID_KEYBOARD_BACKTICK_TILDE   | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_COMMA_LANGLE    (HID_KEYBOARD_COMMA_LANGLE     | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_COMMA           (HID_KEYBOARD_COMMA_LANGLE     | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_LANGLE          (HID_KEYBOARD_COMMA_LANGLE     | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_PERIOD_RANGLE   (HID_KEYBOARD_DOT_RANGLE       | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_PERIOD          (HID_KEYBOARD_DOT_RANGLE       | KEYMAP_UNSHIFTED_KEY)
#define KEYMAP_KEY_RANGLE          (HID_KEYBOARD_DOT_RANGLE       | KEYMAP_SHIFTED_KEY)
#define KEYMAP_KEY_SLASH_QUESTION  (HID_KEYBOARD_SLASH_QUESTION   | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_SLASH           (HID_KEYPAD_SLASH              | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_QUESTION        (HID_KEYBOARD_SLASH_QUESTION   | KEYMAP_SHIFTED_KEY)

#define KEYMAP_KEY_CAPSLOCK    (HID_KEYBOARD_CAPS_LOCK    | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_NUMLOCK     (HID_KEYPAD_NUM_LOCK       | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_SCROLLLOCK  (HID_KEYBOARD_SCROLL_LOCK  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_PRINTSCREEN (HID_KEYBOARD_PRINT_SCREEN | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_PAUSE       (HID_KEYBOARD_PAUSE        | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_INSERT      (HID_KEYBOARD_INSERT       | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_DELETE      (HID_KEYBOARD_DELETE       | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_HOME        (HID_KEYBOARD_HOME         | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_END         (HID_KEYBOARD_END          | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_PAGEUP      (HID_KEYBOARD_PAGE_UP      | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_PAGEDOWN    (HID_KEYBOARD_PAGE_DOWN    | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_LEFT        (HID_KEYBOARD_LEFT_ARROW   | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_DOWN        (HID_KEYBOARD_DOWN_ARROW   | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_UP          (HID_KEYBOARD_UP_ARROW     | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_RIGHT       (HID_KEYBOARD_RIGHT_ARROW  | KEYMAP_HARDWARE_KEY)

#define KEYMAP_KEY_F1  (HID_KEYBOARD_F1  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F2  (HID_KEYBOARD_F2  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F3  (HID_KEYBOARD_F3  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F4  (HID_KEYBOARD_F4  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F5  (HID_KEYBOARD_F5  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F6  (HID_KEYBOARD_F6  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F7  (HID_KEYBOARD_F7  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F8  (HID_KEYBOARD_F8  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F9  (HID_KEYBOARD_F9  | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F10 (HID_KEYBOARD_F10 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F11 (HID_KEYBOARD_F11 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F12 (HID_KEYBOARD_F12 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F13 (HID_KEYBOARD_F13 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F14 (HID_KEYBOARD_F14 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F15 (HID_KEYBOARD_F15 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F16 (HID_KEYBOARD_F16 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F17 (HID_KEYBOARD_F17 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F18 (HID_KEYBOARD_F18 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F19 (HID_KEYBOARD_F19 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F20 (HID_KEYBOARD_F20 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F21 (HID_KEYBOARD_F21 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F22 (HID_KEYBOARD_F22 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F23 (HID_KEYBOARD_F23 | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_F24 (HID_KEYBOARD_F24 | KEYMAP_HARDWARE_KEY)

#define KEYMAP_KEY_LCTRL  (HID_KEYBOARD_LCONTROL | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_LSHIFT (HID_KEYBOARD_LSHIFT   | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_LALT   (HID_KEYBOARD_LALT     | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_LGUI   (HID_KEYBOARD_LGUI     | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_RCTRL  (HID_KEYBOARD_RCONTROL | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_RSHIFT (HID_KEYBOARD_RSHIFT   | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_RALT   (HID_KEYBOARD_RALT     | KEYMAP_HARDWARE_KEY)
#define KEYMAP_KEY_RGUI   (HID_KEYBOARD_RGUI     | KEYMAP_HARDWARE_KEY)
